CollegeMart-master/collegemart/buyer/urls.py
from django.urls import path, include
from . import views
from cart import views as cart_views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'buyer'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('shop/<int:rec>', views.shop_list, name='shop'),
    path('shop/<int:rec>/<int:cid>/<int:sid>', views.shop_filters, name='shop-filters'),
    path('shop/<int:cid>/<int:rec>', views.shop_category, name='shop-category'),
    path('shop/item/<int:pid>/<int:rec>', views.shop_item, name='shop-item'),
    path('', views.home, name='home'),
    path('checkout/', views.checkout, name="checkout"),
    path('search/', views.search, name='search'),
    path('order/', views.order_create, name='order'),
    path('order/cancel/<pid>', views.order_cancellation, name='order-cancellation'),
    path('shop/sort_product', views.sort_products, name="sort_product")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_remove, name='cart_remove'),
]

CollegeMart-master/collegemart/collegemart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from buyer.views import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
    path('feedback/', include('feedback.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.home, name='home'),
]

CollegeMart-master/collegemart/buyer/models.py
from django.db import models
from seller.models import Products_Selling, Products_Leasing
from django.dispatch import receiver
from django.db.models.signals import post_save

BILLING_TYPES = [
        ('1','COD'),
        ('2','ONLINE'),
]

# Create your models here.
class Orders_Buying(models.Model):
    products_selling = models.ForeignKey("seller.Products_Selling", on_delete=models.CASCADE)
    buyer = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    isConfirmed = models.BooleanField(default=True)
    payment_type = models.CharField(max_length=1, default='1', choices=BILLING_TYPES)


class Orders_Leasing(models.Model):
    products_leasing = models.ForeignKey("seller.Products_Leasing", on_delete=models.CASCADE)
    buyer = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    isConfirmed = models.BooleanField(default=True)
    payment_type = models.CharField(max_length=1, default='1', choices=BILLING_TYPES)

class Notification(models.Model):
    message=models.CharField(max_length=100,default="")
    product=models.ForeignKey(Products_Selling,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)

class Leasing_Notification(models.Model):
    message=models.CharField(max_length=100,default="")
    product=models.ForeignKey(Products_Leasing,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)


@receiver(post_save,sender=Orders_Buying)
def sendnotification(sender,instance,created,**kwargs):
   if created:
       instance.products_selling.available=False
       instance.products_selling.save()
       message=" Your "+str(instance.products_selling.pname)+" was bought by "+str(instance.buyer.user.username)+" !!"
       Notification.objects.create(
           message=message,
           product=instance.products_selling,
       )


@receiver(post_save,sender=Orders_Leasing)
def sendnotification2(sender,instance,created,**kwargs):
   if created:
       instance.products_leasing.available=False
       instance.products_leasing.save()
       message=" Your "+str(instance.products_leasing.pname1)+" was bought by "+str(instance.buyer.user.username)+" !!"
       Leasing_Notification.objects.create(
           message=message,
           product=instance.products_leasing,
       )

CollegeMart-master/collegemart/buyer/views.py
from django.http import HttpResponse
from seller.models import Products_Selling, Category, Products_Leasing
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.conf import settings
from cart.forms import CartAddProductForm
from cart.cart import Cart
from simple_search import search_filter
from django.contrib.auth.models import User

from InvoiceGenerator.create import create_invoice
from collegemart.settings import MEDIA_ROOT
from accounts.models import Profile
from .models import Orders_Buying, Orders_Leasing

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

import json

'''
def index(request):
    return render(request, "buyer/home.html")'''


def shop_list(request, rec=0):
    cart = Cart(request)
    categories = Category.objects.all()
    if rec == 0:
        products = Products_Selling.objects.filter(available=True).order_by('price')
    else:
        products = Products_Leasing.objects.filter(available=True).order_by('leasing_period')
    paginator = Paginator(products, 12)# Show 12 products per page
    page = request.GET.get('page')
    products = paginator.get_page(page)
    context = {'products':products, 'categories':categories, 'rec':rec, 'cart': cart}
    return render(request, "buyer/shop.html", context)

def shop_filters(request, rec,cid, sid=1):
    category = Category.objects.get(pk=cid)
    c = Category.objects.all()
    products_list = Products_Selling.objects.filter(category=category)
    if(sid==1):
        products_list = Products_Selling.objects.filter(category=category).order_by('price')
    elif(sid==2):
        products_list = Products_Selling.objects.filter(category=category).order_by('-price')
    paginator = Paginator(products_list, 12)  # Show 12 products per page
    page = request.GET.get('page')
    products = paginator.get_page(page)
    context = {'products': products, 'categories': c, 'cid':cid, 'rec': 0, 'category': category}
    return render(request, "buyer/shop-category.html", context)

def shop_category(request, cid, rec=0):
    cart = Cart(request)
    category = Category.objects.get(pk=cid)
    categories = Category.objects.all()
    if rec == 0:
        products_list = Products_Selling.objects.filter(category=category, available=True)
    else:
        products_list = Products_Leasing.objects.filter(category1=category, available=True)
    paginator = Paginator(products_list, 12)  # Show 12 products per page
    page = request.GET.get('page')
    products = paginator.get_page(page)
    context = {'products': products , 'categories': categories,'category': category, 'rec': rec, 'cart': cart}
    return render(request, "buyer/shop-category.html", context)

@login_required
def shop_item(request, pid, rec):
    cart = Cart(request)
    if rec == 0:
        product = Products_Selling.objects.get(pk=pid)
    else:
        product = Products_Leasing.objects.get(pk=pid)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form, 'rec': rec, 'cart': cart}
    return render(request, 'buyer/shop-item.html', context)

def home(request):
    user = User.objects.none()
    if request.user.is_authenticated:
        user = request.user
    cart = Cart(request)
    return render(request, 'buyer/index.html', {'cart': cart, 'user': user})


def about(request):
    return render(request, 'buyer/about.html', {'title': 'About'})

@login_required
def checkout(request):
    cart = Cart(request)
    return render(request, 'buyer/checkout.html', {'cart': cart})

@login_required
def search(request):
    if request.method == 'GET':
        search_query = request.GET.get('search_box',None)
        print(search_query)
        if search_query:
            mylist=search_query.split(' ')
            prod_s=Products_Selling.objects.none()
            prod_l=Products_Leasing.objects.none()
            for elements in mylist:
                    search_fields = ['pname', 'description']
                    f = search_filter(search_fields,elements)
                    filtered = Products_Selling.objects.filter(f)
                    if filtered.exists():
                        prod_s=prod_s.union(filtered)
                    search_fields1=['^pname1', 'description1']
                    g=search_filter(search_fields1,elements)
                    filtered1=Products_Leasing.objects.filter(g)
                    if filtered1.exists():
                        prod_l=prod_l.union(filtered1)
            if len(prod_s)!=0 or len(prod_l)!=0:
                return render(request, 'buyer/search.html', {'products': prod_s})
            else:
                return redirect('seller:request')
        return redirect('buyer:home')

@login_required
def order_create(request):
    if request.method == 'POST':
        mode = request.POST['mode']
        if mode == '1':
            cart = Cart(request)
            profile = Profile.objects.get(user=request.user)
            for item in cart:
                rec = int(item['rec'])
                if rec == 0:
                    order = Orders_Buying.objects.create(products_selling = item['sproduct'], buyer = profile, payment_type=mode)
                    p = Products_Selling.objects.filter(id = item['sproduct'].id)[0]
                    p.available = False
                    p.save()
                else:
                    Orders_Leasing.objects.create(products_leasing = item['lproduct'], buyer = profile, payment_type=mode)
                    p = Products_Leasing.objects.filter(id = item['lproduct'].id)[0]
                    p.available = False
                    p.save()
                profile = Profile.objects.get(user = request.user)
                create_invoice(profile, order)
                current_site = get_current_site(request)
                mail_subject = 'Your Order Invoice.'
                message = render_to_string('buyer/order_email.html')
                to_email = request.user.email
                email = EmailMessage(
                            mail_subject, message, to=[to_email]
                )
                email.attach_file(MEDIA_ROOT+'/orders/'+str(order.id)+".pdf")
                email.send()
            return redirect('buyer:home')
        else:
            cart = Cart(request)
            profile = Profile.objects.get(user=request.user)
            for item in cart:
                rec = int(item['rec'])
                if rec == 0:
                    order = Orders_Buying.objects.create(products_selling = item['sproduct'], buyer = profile, payment_type=mode)
                    p = Products_Selling.objects.filter(id = item['sproduct'].id)[0]
                    p.available = False
                    p.save()
                else:
                    Orders_Leasing.objects.create(products_leasing = item['lproduct'], buyer = profile, payment_type=mode)
                    p = Products_Leasing.objects.filter(id = item['lproduct'].id)[0]
                    p.available = False
                    p.save()
                profile = Profile.objects.get(user = request.user)
                create_invoice(profile, order)
                current_site = get_current_site(request)
                mail_subject = 'Your Order Invoice.'
                message = render_to_string('buyer/order_email.html')
                to_email = request.user.email
                email = EmailMessage(
                            mail_subject, message, to=[to_email]
                )
                email.attach_file(MEDIA_ROOT+'/orders/'+str(order.id)+".pdf")
                email.send()
            return redirect('paytm:payment')

@login_required
def order_cancellation(request, pid):
    o=Orders_Buying.objects.get(pk=pid)
    p = o.products_selling
    p.available = True
    p.save()
    message=" The order for "+str(o.products_selling.pname)+" has been cancelled by "+str(o.buyer.user.username)+" !!"
    Notification.objects.create(
        message=message,
        product=p,
    )
    o.delete()
    return redirect('buyer:home')

def sort_products(request):
    if request.method == 'GET':
        sort_text = request.POST.get('filter')
        response_data = {}
        
        if sort_text == '1':
            p = Products_Selling.objects.filter().order_by('price')
        else:
            p = Products_Selling.objects.filter().order_by('-price')
            v = list(p.values())
            k = []
            count = 0
            for c in v:
                k.append({})
                for key,value in c.items():
                    if key == 'id' or key == 'pname'or key == 'rating':
                        k[count][key] = value
                    elif key == 'price':
                        k[count][key] = str(value)
                count += 1
        response_data['products'] = k
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        return HttpResponse(json.dumps({"nothing to see": "this isn't happening"}), content_type="application/json")

CollegeMart-master/collegemart/buyer/templates/buyer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="shortcut icon" type="image/png" href="{% static 'images/logo_favic.png' %}">
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block ascript %}
    {% endblock %}

</head>

<body onload="reload()">
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="{% url 'buyer:search' %}" method="get">
                            <input type="search" name="search_box" id="search_box" placeholder="Type your keyword...">
                            <button type="submit"><img src="{% static 'img/core-img/search.png' %}" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-content-wrapper d-flex clearfix">

        <div class="mobile-nav">
            <div class="amado-navbar-brand">
                <a href="{% url 'buyer:home' %}"><img src="{% static 'img/logo_cm.png' %}" alt=""></a>
            </div>
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <header class="header-area clearfix">
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <div class="logo">
                <a href="{% url 'buyer:home' %}"><img src="{% static 'img/logo_cm.png' %}" alt=""></a>
            </div>
            <nav class="amado-nav">
                <ul>
                    <li class="active"><a href="{% url 'buyer:home' %}">Home</a></li>
                    <li><a href="{% url 'buyer:shop' 0 %}">Shop</a></li>
                    {% if user.is_authenticated %}
                    <li class=""><a href="{% url 'my-profile' %}">View Profile</a></li>
                    <li clas=""><a href="{% url 'change_password' %}">Change Password</a></li>
                    <li class=""><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li class=""><a href="{% url 'login' %}">Login</a></li>
                    <li class=""><a href="{% url 'register' %}">Sign Up</a></li>
                    {% endif %}
                    {% if cart|length %}
                    <li><a href="{% url 'buyer:checkout' %}">Checkout</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="cart-fav-search mb-100">
                <a href="{% url 'cart:cart_detail' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart|length }})</span></a>
                <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
            </div>
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        {% block content %} {% endblock %}

    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <div class="footer-logo mr-50">
                            <a href="{% url 'buyer:home' %}"><img src="{% static 'img/logo_cm.png' %}" alt=""></a>
                        </div>
                        <p class="copywrite">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="{% url 'buyer:home' %}" target="_blank">CollegeMart</a>
</p>
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'buyer:home' %}">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'buyer:shop' 0 %}">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'buyer:checkout' %}">Checkout</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'feedback:home' %}">Feedback</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
    {% block script %}
    {% endblock %}

</body>

</html>

CollegeMart-master/collegemart/buyer/templates/buyer/order_email.html
{% autoescape off %}
Hey there! 
Your order's been placed and will be delivered to you soon.
Thanks a lot!
{% endautoescape %}

CollegeMart-master/collegemart/buyer/templates/buyer/shop-category.html
{% extends "buyer/base.html" %}
{% load static %}
{% block content %}
<div class="shop_sidebar_area">

            <!-- ##### Single Widget ##### -->
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Categories</h6>

                <!--  Catagories  -->
                <div class="catagories-menu">
                    <ul>
                        {% for c in categories %}
                        <li><a href="{% url 'buyer:shop-category' c.id 0%}">{{ c.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Type of Order</h6>

                <!--  Catagories  -->
                <div class="catagories-menu">
                    <ul>
                        <li><a href="{% url 'buyer:shop' 0 %}">Selling</a></li>
                        <li><a href="{% url 'buyer:shop' 1 %}">Leasing</a></li>
                    </ul>
                </div>
            </div>

            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Sorting</h6>

                <!--  Catagories  -->
                <div class="catagories-menu">
                    <ul>
                        <li><a href="{% url 'buyer:shop-filters' rec category.id 1 %}">Low to High</a></li>
                        <li><a href="{% url 'buyer:shop-filters' rec category.id 2 %}">High to Low</a></li>
                    </ul>
                </div>
            </div>

            <!-- ##### Single Widget ##### -->
        </div>
            <div class="amado_product_area section-padding-100">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <div class="product-topbar d-xl-flex align-items-end justify-content-between">
                            <!-- Total Products -->
                            <div class="total-products">
                                <p>Showing 12 items</p>
                                <div class="view d-flex">
                                    <a href="#"><i class="fa fa-th-large" aria-hidden="true"></i></a>
                                </div>
                            </div>
                            <ul class="navbar-nav">
                                <li class="nav-item" style="margin-left: 7px;">
                                    <form action="{% url 'seller:saleform.home' %}">
                                        <button class="btn" type="submit" value="products to be sold" style="border-radius:0px ">Post AD for sale</button>
                                    </form>
                                </li>
                            </ul>
                                                    <!-- Sorting -->
                            
                        </div>
                    </div>
                </div>
                <div class="row" id="prodRow">
                    {% if rec == 0 %}
                    <!-- Single Product Area -->
                        {% for product in products %}
                    <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                        <div class="single-product-wrapper">
                            <!-- Product Image -->
                            <div class="product-img">
                                <a href="{% url 'buyer:shop-item' product.pk rec %}"><img src="{{ product.image.url }}" alt="" style="width:500px; height:500px;"></a>
                                <!-- Hover Thumb -->
                                <div class="hover-content">
                                    <div class="line"></div>
                                </div>
                            </div>

                            <!-- Product Description -->
                            <div class="product-description d-flex align-items-center justify-content-between">
                                <!-- Product Meta Data -->
                                <div class="product-meta-data">
                                    <div class="line"></div>
                                    <p class="product-price">₹{{ product.price }}</p>
                                    <a href="{% url 'buyer:shop-item' product.pk rec %}">
                                        <h6>{{ product.pname }}</h6>
                                    </a>
                                </div>
                                <!-- Ratings & Cart -->
                                <div class="ratings-cart text-right">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="cart">
                                        <a href="{% url 'cart:cart_add' product.pk rec %}" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="{% static 'img/core-img/cart.png' %}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        {% endfor %}
                    {% else %}
                        {% for product in products %}
                    <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                        <div class="single-product-wrapper">
                            <!-- Product Image -->
                            <div class="product-img">
                                <a href="{% url 'buyer:shop-item' product.pk rec %}"><img src="{{ product.image1.url }}" alt="" style="width:500px; height:500px;"></a>
                                <!-- Hover Thumb -->
                                <div class="hover-content">
                                    <div class="line"></div>
                                </div>
                            </div>

                            <!-- Product Description -->
                            <div class="product-description d-flex align-items-center justify-content-between">
                                <!-- Product Meta Data -->
                                <div class="product-meta-data">
                                    <div class="line"></div>
                                    <p class="product-price">₹{{ product.price1 }}</p>
                                    <a href="{% url 'buyer:shop-item' product.pk rec %}">
                                        <h6>{{ product.pname1 }}</h6>
                                    </a>
                                </div>
                                <!-- Ratings & Cart -->
                                <div class="ratings-cart text-right">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="cart">
                                        <a href="{% url 'cart:cart_add' product.pk rec %}" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="img/core-img/cart.png" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        {% endfor %}
                    {% endif %}


            </div>


<div class="row">
                    <div class="col-12">
                        <!-- Pagination -->
                        <nav aria-label="navigation">
                            <ul class="pagination justify-content-end mt-50">
                                {% if products.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ contacts.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                <li class="page-item active"><a class="page-link" href="#">{{ products.number }}</a></li>
                                {% if products.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">Last</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}