CollegeMart-master/collegemart/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_remove, name='cart_remove'),
]

CollegeMart-master/collegemart/collegemart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from buyer.views import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
    path('feedback/', include('feedback.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/seller/urls.py
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name = 'seller'

urlpatterns=[
    path('',views.productsale,name="saleform.home"),
    path('sale/',views.tosell,name="tosell"),
    path('sale/<pid><n>', views.deletion, name="tosell"),
    path('request/', views.Request, name="request"),
]

CollegeMart-master/collegemart/seller/models.py
from django.db import models
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
'''
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
'''

class Products_Selling(models.Model):
    category = models.ForeignKey(Category, related_name='products_selling', on_delete=models.CASCADE)
    pname = models.CharField(max_length=100, blank=False, null=False, db_index=True)
#    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=False, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    stock = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    rating = models.FloatField(null=False, default=0)
    image = models.ImageField(upload_to='SellingProductsPhotos', blank=False)
    seller = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
 
    def __str__(self):
        return self.pname
    
'''
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
'''

class Products_Leasing(models.Model):
    category1 = models.ForeignKey(Category, related_name='products_leasing', on_delete=models.CASCADE)
    pname1 = models.CharField(max_length=100, blank=False, null=False, db_index=True)
#    slug = models.SlugField(max_length=100, db_index=True)
    description1 = models.TextField(blank=False, null=False)
    price1 = models.DecimalField(max_digits=10, decimal_places=2, default=50)
    stock = models.PositiveIntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    rating = models.FloatField(null=False, default=0)
    image1 = models.ImageField(upload_to='LeasingProductsPhotos', blank=False)
    leaser = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    leasing_period = models.IntegerField(null=False, blank=False)
    start_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.pname1

class Request_table(models.Model):
    pname2 = models.CharField(max_length=100, blank=False, null=False)
    description2 = models.TextField(blank=False, null=False)
    person = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    def __str__(self):
        return self.pname2

    def __repr__(self):
        return self.pname2

class commonNotification(models.Model):
    message=models.CharField(max_length=100,default="")
    request=models.ForeignKey(Request_table,on_delete=models.CASCADE,default='')
    status=models.BooleanField(default=False)


@receiver(post_save,sender=Request_table)
def sendnotification(sender,instance,created,**kwargs):

   if created:
       message=" One of your collegemates needs "+str(instance.pname2)+".If you have it, you can post an ad."
       commonNotification.objects.create(
           message=message,
           request=instance
       )

CollegeMart-master/collegemart/seller/forms.py
from django import forms
from . models import Products_Selling, Products_Leasing, Request_table

class saleform(forms.ModelForm):

    class Meta:
        model = Products_Selling
        fields = ('pname', 'description','image','category', 'price')

class leaseform(forms.ModelForm):

    class Meta:
        model = Products_Leasing
        fields = ('pname1', 'description1','image1','category1', 'leasing_period')

class requestform(forms.ModelForm):

    class Meta:
        model = Request_table
        fields = ('pname2','description2')

CollegeMart-master/collegemart/seller/views.py
from functools import reduce
from django.shortcuts import render,redirect, render_to_response
from django.template import RequestContext
from . models import Products_Selling, Products_Leasing
from accounts.models import Profile
from . forms import saleform, leaseform, requestform
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from simple_search import search_filter
from django.urls import reverse

# Create your views here.

@login_required()
def productsale(request):
    profile = Profile.objects.filter(user=request.user)[0]
    if request.method == 'POST':
        form3=saleform(request.POST, request.FILES)
        form5=leaseform(request.POST, request.FILES)
        if form3.is_valid():
            p = Profile.objects.filter(user=request.user)[0]
            product = form3.save(commit=False)
            product.seller = p
            product.save()
            return redirect('buyer:home')
        if form5.is_valid():
            p = Profile.objects.filter(user=request.user)[0]
            product = form5.save(commit=False)
            product.leaser = p
            product.save()
            return redirect('buyer:home')
        else:
            form3 = saleform()
            form5 = leaseform()
            return render(request, 'seller/saleform.html', {'form3': form3,'form5':form5, 'profile': profile})
        return redirect('buyer:home')    
    else:
        form3 = saleform()
        form5 = leaseform()
        return render(request, 'seller/saleform.html', {'form3': form3,'form5':form5, 'profile': profile})


@login_required()
def tosell(request):
    p = Profile.objects.get(user=request.user)
    m = Products_Selling.objects.filter(seller=p)
    n = Products_Leasing.objects.filter(leaser=p)
    if request.method == 'GET':
        search_query = request.GET.get('search_box',None)
        print(search_query)
        if search_query:
            mylist=search_query.split(' ')
            inst=[]
            for elements in mylist:
                    search_fields = ['^pname', 'description']
                    f = search_filter(search_fields,elements)
                    filtered = Products_Selling.objects.filter(f)
                    if filtered.exists():
                        inst.append(filtered)
                    else:
                        return render(request, 'seller/tosell.html', {'m': m,'n':n})
            return render(request, 'seller/search.html', {'inst': inst})
        else:
            return render(request, 'seller/tosell.html', {'m': m,'n':n})
    else:
        return render(request, 'seller/tosell.html', {'m': m,'n':n})

def deletion(request,pid,n='0'):
    if n=='0':
        a=Products_Selling.objects.filter(pk=pid)
        a.delete()
    else:
        a = Products_Leasing.objects.filter(pk=pid)
        a.delete()
    return redirect('view-my-products')

def Request(request):
    p = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form7 = requestform(request.POST)
        if form7.is_valid():
            p = Profile.objects.filter(user=request.user)[0]
            product = form7.save(commit=False)
            product.person = p
            print(product.person)
            product.save()
            return redirect('seller:saleform.home')
        else:
            form7=requestform()
            return render(request, 'seller/request.html', {'form7':form7, 'profile': p})
    else:
        form7 = requestform()
        return render(request, 'seller/request.html', {'form7': form7, 'profile': p})

CollegeMart-master/collegemart/seller/templates/seller/request.html
{% extends 'buyer/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<head>
    {% block ascript %}
    <style>
    body{
        background-color:whitesmoke;
        background-repeat: no-repeat;
        background-size:100% 100%;
        background-attachment:fixed;
    }

    #id_description,#id_description1,#id_description2{
        height:10em;

    }
    .button {
      background-color: rgba(251, 183, 16, 0.96);
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      font-size: 16px;
      margin: 4px 2px;
      opacity: 1;
      transition: 0.3s;
    }

    .button:hover {opacity: 0.6;box-shadow:3px 5px 7px #888888}

    button {
      background-color: rgba(251, 183, 16, 0.96);
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      font-size: 16px;
      margin: 4px 2px;
      opacity: 1;
      transition: 0.3s;
    }

    button:hover {opacity: 0.6;box-shadow:3px 5px 7px #888888}

    </style>

    <script type="text/javascript">

        $(function () {
            $('#id_pname2').addClass('form-control mb-4 transparent-input').attr("placeholder", "Product name");
            $("#id_description2").addClass("form-control mb-4 transparent-input").attr("placeholder", "Describe the product");
        });

    </script>
    {% endblock %}

</head>
{% block content %}
<body onload="reload()">
<div onload="reload()">
    <div id="salead"
     style="box-shadow:5px 10px 15px #888;width: 700px;margin-left: 30%;margin-top:2%; background-color:white;border-color: white;border-width: 1.5px;">
    <div  style="padding-left: 10%;padding-right: 10%;padding-bottom:7%;background-color: white;padding-top: 5%;margin-top: 17%;">
        <form action="{% url 'seller:request' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12 display-3 " style="color: darkslategrey;">
                        POST REQUEST
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            Product name:
                            {{form7.pname2}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            DESCRIPTION:
                            {{form7.description2}}

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                             <input type="submit" value="Request for an item" class="button" style="width: 100%;">

                        </div>
                    </div>
        </form>
    </div>
</div>
</div>
</div>
<script>
    function reload(){
    $('#page').fadeIn(500)
}
</script>
</body>
{% endblock content %}

CollegeMart-master/collegemart/seller/templates/seller/saleform.html
{% extends 'buyer/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<head>
    {% block ascript %}
    <style>
    body{
        background-color:whitesmoke;
        background-repeat: no-repeat;
        background-size:100% 100%;
        background-attachment:fixed;
    }

    #id_description,#id_description1,#id_description2{
        height:10em;

    }
    .button {
      background-color: rgba(251, 183, 16, 0.96);
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      font-size: 16px;
      margin: 4px 2px;
      opacity: 1;
      transition: 0.3s;
    }

    .button:hover {opacity: 0.6;box-shadow:3px 5px 7px #888888}

    button {
      background-color: rgba(251, 183, 16, 0.96);
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      font-size: 16px;
      margin: 4px 2px;
      opacity: 1;
      transition: 0.3s;
    }

    button:hover {opacity: 0.6;box-shadow:3px 5px 7px #888888}

    </style>

    <script type="text/javascript">

        $(function () {
            $('#id_pname').addClass('form-control mb-4 transparent-input').attr("placeholder", "Product name");
            $("#id_category").addClass("form-control mb-4 transparent-input");
            $('#id_image').addClass('form-control-file transparent-input');
            $("#id_description").addClass("form-control mb-4 transparent-input").attr("placeholder", "Describe the product");
            $('#id_price').addClass('form-control mb-4 transparent-input').attr("placeholder", "Price of the product");
            $('#id_leasing_period').addClass('form-control mb-4 transparent-input').attr("placeholder", "leasing period");
            $('#id_pname1').addClass('form-control mb-4 transparent-input').attr("placeholder", "Product name");
            $("#id_category1").addClass("form-control mb-4 transparent-input");
            $('#id_image1').addClass('form-control-file transparent-input');
            $("#id_description1").addClass("form-control mb-4 transparent-input").attr("placeholder", "Describe the product");
            $("#id_price1").addClass("form-control mb-4 transparent-input").attr("placeholder", "Price of the product");

        });

    </script>
    {% endblock %}

</head>
{% block content %}
<div>
    <div id="salead"
     style="box-shadow:5px 10px 15px #888;display:none ;width: 700px;margin-left: 30%;margin-top:2%; background-color:white;border-color: white;border-width: 1.5px;">
    <div  style="padding-left: 10%;padding-right: 10%;padding-bottom:7%;background-color: white">
        <form action="{% url 'seller:saleform.home' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-8 display-2">
                    <p style="font-size: 80px;color: darkslategrey;">POST AD</p>
                </div>
                <div class="col-lg-4 display-2 ">
                    <button onclick="lease()">Leasing Ad</button>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    Product name:
                    {{form3.pname}}
                </div>
                <div class="col-lg-6">
                    Amount:
                    {{form3.price}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    Photo:
                    {{form3.image}}
                </div>
                <div class="col-lg-6">
                    Category:<br>
                    {{form3.category}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
               <br>     DESCRIPTION:
                    {{form3.description}}

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                     <input type="submit" value="POST AD" class="button" style="width: 100%;font-size:20px ">

                </div>
            </div>
        </form>
    </div>
</div>
<div id="leasead"
     style="box-shadow:5px 10px 15px #888;display:none ;width: 700px;margin-left: 30%;margin-top:2%; background-color:white;border-color: white;border-width: 1.5px;">
    <div style="padding-left: 10%;padding-right: 10%;padding-bottom:7%;background-color: white">
        <form action="{% url 'seller:saleform.home' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-8 display-2">
                <p style="font-size: 80px;color: darkslategrey;">POST AD</p>
                </div>
                <div class="col-lg-4 display-2">
                    <button onclick="sale()">sale Ad</button>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    Product name:
                    {{form5.pname1}}
                </div>
                <div class="col-lg-6">
                    Leasing Period(in months):
                    {{form5.leasing_period}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    Photo:
                    {{form5.image1}}
                </div>
                <div class="col-lg-6">
                    Category:<br>
                    {{form5.category1}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                 <br>   DESCRIPTION:
                    {{form5.description1}}

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                     <input type="submit" value="post ad" class="button" style="width: 100%;">

                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
<script>

function lease(){
    $('#salead').fadeOut(500);
    $('#leasead').delay(500).fadeIn(500);
}
function sale(){
    $('#leasead').fadeOut(500);
    $('#salead').delay(500).fadeIn(500);
}
function reload(){
    $('#salead').fadeIn(500)
}
</script>
{% endblock content %}

CollegeMart-master/collegemart/seller/templates/seller/saleform1.html
{% extends 'buyer/base.html' %}
{% load crispy_forms_tags %}
<head>
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>


        .btn:hover {
            opacity: 0.6;
            box-shadow: 3px 6px 8px #888888;
        }
    </style>
    {% block ascript %}
    <script type="text/javascript">

        $(function () {
            $('#id_pname').addClass('form-control mb-4 transparent-input').attr("placeholder", "Product name");
            $("#id_category").addClass("form-control mb-4 transparent-input");
            $('#id_image').addClass('form-control-file transparent-input');
            $("#id_description").addClass("form-control mb-4 transparent-input").attr("placeholder", "Describe the product");
            $('#id_price').addClass('form-control mb-4 transparent-input').attr("placeholder", "Price of the product");
            $('#id_leasing_period').addClass('form-control mb-4 transparent-input').attr("placeholder", "leasing period");
            $('#id_pname1').addClass('form-control mb-4 transparent-input').attr("placeholder", "Product name");
            $("#id_category1").addClass("form-control mb-4 transparent-input");
            $('#id_image1').addClass('form-control-file transparent-input');
            $("#id_description1").addClass("form-control mb-4 transparent-input").attr("placeholder", "Describe the product");
            $("#id_price1").addClass("form-control mb-4 transparent-input").attr("placeholder", "Price of the product");

        });

    </script>
    {% endblock %}
</head>
{% block content %}
<div class="container" style="top:50px; width:100px;">
</div>
<div class="container"  style="background-color: white;box-shadow:10px 10px 15px #888888; width: 500px;margin-right: 30%; margin-top: 13.5%;margin-bottom:16%">
      <h2 style="font-family: helveticaneuemedium;text-transform: uppercase;color: darkslategrey;">Post Ad For Sale/Lease</h2>
        <div class="content" id="salead">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header" style="background-color: #fbb710; color: white">
                                <strong>Add Product Selling</strong> Form
                            </div>
                            <div class="row form-group">
                                <div class="col-12 col-md-9">
                                        <button type="submit" class="btn btn-outline-secondary" onclick="lease()">
                                            Leasing Ad
                                        </button>
                                </div>
                                
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'seller:saleform.home' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Product Name :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{form3.pname}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Category :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{form3.category}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Amount :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form3.price }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">Photo :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form3.image }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">Description :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form3.description }}
                                        </div>
                                    </div>

                                    <div class="row form-group">
    <button type="submit" class="btn" style="border-radius: 0;border-color:#fbb710;background-color: #fbb710;color:white;">Submit</button>
                                    </div>
                                </form>
                            </div>

                    </div>
                </div>
        </div>
    </div>
<div class="content" id="leasead">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header" style="background-color: #fbb710; color: white">
                                <strong>Add Product Leasing</strong> Form
                            </div>
                            <div class="row form-group">
                                <div class="col-12 col-md-9">
                                        <button type="submit" class="btn btn-outline-secondary" onclick="sale()">
                                            Selling Ad
                                        </button>
                                </div>
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'seller:saleform.home' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Product Name :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{form5.pname1}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Category :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{form5.category1}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Leasing Period :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form5.leasing_period }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Amount :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form5.price1 }}
                                        </div>
                                    </div>

                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">Photo :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form5.image1 }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">Description :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form5.description1 }}
                                        </div>
                                    </div>

                                    <div class="row form-group">
    <button type="submit" class="btn" style="border-radius: 0;border-color:#fbb710;background-color: #fbb710;color:white;">Submit</button>
                                    </div>
                                </form>
                            </div>

                    </div>
                </div>
        </div>
    </div>
    </div>
    </div>
    <script>
function lease(){
    $('#salead').fadeOut(500);
    $('#leasead').delay(500).fadeIn(500);
}
function sale(){
    $('#leasead').fadeOut(500);
    $('#salead').delay(500).fadeIn(500);
}
function reload(){
    $('#salead').fadeIn(500)
    $('#leasead').fadeOut(500)
}
</script>
{% endblock content %}

CollegeMart-master/collegemart/seller/templates/seller/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for item in inst %}
        {% for val in item %}
            {{val.pname}}<br>
            {{val.description}}<br>
            -----------------<br><br>
        {% endfor %}
    {% endfor %}
</body>
</html>