CollegeMart-master/collegemart/accounts/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # url(r'^account/$', views.account, name='account'),
    # url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),

    #path('accounts/', views.accounts, name='accounts'),
    #path('explore/',views.explore,name='explore'),
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('login/', views.login, name='login'),
    #path('logout/', views.logout, name='logout'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page = '/accounts/login/'), name='logout'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^register/$', views.signup, name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    url(r'^reset-password/$', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html', email_template_name="accounts/reset_password_email.html", subject_template_name='accounts/password_reset_subject.txt'), name="password_reset"),
    url(r'^reset-password/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name="password_reset_done"),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    url(r'^reset-password/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    path('admin/user_table/', views.user_show, name='user-show'),
    path('admin/edit_user_select/', views.admin_edit_user_show, name='edit-user-show'),
    path('admin/edit_user/<uid>', views.admin_edit_user, name='admin-edit-user'),
    path('admin/admin_add_user/', views.admin_add_user, name='admin-add-user'),
    path('admin/add_product/', views.admin_add_product, name='admin-add-product'),
    path('admin/product_table/', views.product_show, name='product-show'),
    path('admin/edit_product_select/', views.admin_edit_product_show, name='edit-product-show'),
    path('admin/edit_product/<pid>', views.admin_edit_product, name='admin-edit-product'),
    path('admin/delete_product_select/', views.admin_delete_product_show, name='delete-product-show'),
    path('admin/delete_product/<pid>', views.admin_delete_product, name='admin-delete-product'),
    path('admin/dashboard/',  views.admin_dashboard, name='dashboard'),
    path('admin/order_table/', views.order_show, name='order-show'),
    path('logged_in/', views.logged_in, name='after-login'),
    path('profile/', views.my_profile, name='my-profile'),
    path('edit_my_profile/', views.edit_profile, name='edit-my-profile'),
    path('dashboard/', views.login_dashboard, name='login-dashboard'),
    path('admin/view_invoice_show/', views.admin_invoices_show, name='view-invoice-select'),
    path('admin/view_invoice/<iid>', views.admin_view_invoice, name='admin-view-invoice'),
    path('view_my_invoice/', views.my_invoices_show, name='my-invoices'),
    path('view_invoice/<iid>', views.login_view_invoice, name='view-my-invoice'),
    path('my_orders/',views.myorder, name='my-orders-show'),
    path('my_orders/<pid><n>', views.cancellation, name='my-orders-show'),
    path('admin/requests_show/', views.admin_requests_show, name='admin-requests-show'),
    path('admin/requests_show/<rid>', views.admin_delete_request, name='admin-delete-request'),
    path('view_my_products/', views.view_my_products, name="view-my-products"),
    path('admin/my_profile/', views.admin_profile, name='admin-profile'),
    path('admin/edit_profile/', views.admin_edit_profile, name='admin-edit-profile'),
    path('send_invoice/<oid>', views.Send_Invoice, name='send-invoice-to')
]

CollegeMart-master/collegemart/buyer/urls.py
from django.urls import path, include
from . import views
from cart import views as cart_views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'buyer'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('shop/<int:rec>', views.shop_list, name='shop'),
    path('shop/<int:rec>/<int:cid>/<int:sid>', views.shop_filters, name='shop-filters'),
    path('shop/<int:cid>/<int:rec>', views.shop_category, name='shop-category'),
    path('shop/item/<int:pid>/<int:rec>', views.shop_item, name='shop-item'),
    path('', views.home, name='home'),
    path('checkout/', views.checkout, name="checkout"),
    path('search/', views.search, name='search'),
    path('order/', views.order_create, name='order'),
    path('order/cancel/<pid>', views.order_cancellation, name='order-cancellation'),
    path('shop/sort_product', views.sort_products, name="sort_product")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_remove, name='cart_remove'),
]

CollegeMart-master/collegemart/collegemart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from buyer.views import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
    path('feedback/', include('feedback.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from collegemart.settings import MEDIA_ROOT

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fname = models.CharField(max_length=100, blank=False)
    lname = models.CharField(max_length=100, blank=True)
    dob = models.DateField(("DOB"), blank=False)
    phone = PhoneNumberField(null=False, blank=False, unique=True)
    rating = models.FloatField(null=False, default=0)
    photo = models.ImageField(upload_to='ProfilePhotos/', null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def __repr__(self):
        return self.user.username

    def __unicode__(self):
        return u'Profile of user: %s' % self.user.username

CollegeMart-master/collegemart/seller/models.py
from django.db import models
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
'''
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
'''

class Products_Selling(models.Model):
    category = models.ForeignKey(Category, related_name='products_selling', on_delete=models.CASCADE)
    pname = models.CharField(max_length=100, blank=False, null=False, db_index=True)
#    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=False, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    stock = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    rating = models.FloatField(null=False, default=0)
    image = models.ImageField(upload_to='SellingProductsPhotos', blank=False)
    seller = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
 
    def __str__(self):
        return self.pname
    
'''
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
'''

class Products_Leasing(models.Model):
    category1 = models.ForeignKey(Category, related_name='products_leasing', on_delete=models.CASCADE)
    pname1 = models.CharField(max_length=100, blank=False, null=False, db_index=True)
#    slug = models.SlugField(max_length=100, db_index=True)
    description1 = models.TextField(blank=False, null=False)
    price1 = models.DecimalField(max_digits=10, decimal_places=2, default=50)
    stock = models.PositiveIntegerField(default=1)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    rating = models.FloatField(null=False, default=0)
    image1 = models.ImageField(upload_to='LeasingProductsPhotos', blank=False)
    leaser = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    leasing_period = models.IntegerField(null=False, blank=False)
    start_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.pname1

class Request_table(models.Model):
    pname2 = models.CharField(max_length=100, blank=False, null=False)
    description2 = models.TextField(blank=False, null=False)
    person = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    def __str__(self):
        return self.pname2

    def __repr__(self):
        return self.pname2

class commonNotification(models.Model):
    message=models.CharField(max_length=100,default="")
    request=models.ForeignKey(Request_table,on_delete=models.CASCADE,default='')
    status=models.BooleanField(default=False)


@receiver(post_save,sender=Request_table)
def sendnotification(sender,instance,created,**kwargs):

   if created:
       message=" One of your collegemates needs "+str(instance.pname2)+".If you have it, you can post an ad."
       commonNotification.objects.create(
           message=message,
           request=instance
       )

CollegeMart-master/collegemart/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from phonenumber_field.formfields import PhoneNumberField
from seller.models import Products_Selling

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    def clean_email(self):
        data = self.cleaned_data['email']
        domain = data.split('@')[1]
        domain_list = ["iiits.in",]
        if domain not in domain_list:
            raise forms.ValidationError("Please enter an Email Address with a valid domain")
        return data
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProfileForm(forms.ModelForm):
    fname = forms.CharField(max_length=100, help_text='Required')
    lname = forms.CharField(max_length=100, help_text='Required')
    dob = forms.DateField(help_text='Required')
    phone = PhoneNumberField(help_text='Required')
    photo = forms.ImageField()
    bio = forms.Textarea()

    class Meta:
        model = Profile
        fields = ('fname', 'lname', 'dob', 'phone', 'photo', 'bio')
        widgets = {
            'dob': forms.DateInput(attrs={'class':'dob'}),
        }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('fname', 'lname', 'dob', 'phone', 'photo', 'bio')
        widgets = {
            'dob': forms.DateInput(attrs={'class': 'dob'}),
        }

class AdminAddProductForm(forms.ModelForm):
    class Meta:
        model = Products_Selling
        fields = ('pname', 'description', 'image', 'category', 'price', 'seller')

class AdminEditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'is_active')


class AdminEditProductForm(forms.ModelForm):
    class Meta:
        model = Products_Selling
        fields = ('description', 'image', 'category', 'price')

CollegeMart-master/collegemart/accounts/templates/my template/admin_edit_product_form.html
{% extends 'my template/demo_body.html' %}

{% block script %}
    <script type="text/javascript">
        $(function () {
            $('#id_pname').addClass("form-control mb-4");
            $("#id_category").addClass("form-control mb-4");
            $("#id_description").addClass("form-control mb-4");
            $('#id_price').addClass("form-control mb-4");
             $('#id_image').addClass('form-control-file');

        });

    </script>
{% endblock %}


{% block table %}
        <div class="breadcrumbs">
            <div class="breadcrumbs-inner">
                <div class="row m-0">
                    <div class="col-sm-4">
                        <div class="page-header float-left">
                            <div class="page-title">
                                <h1>Dashboard</h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="page-header float-right">
                            <div class="page-title">
                                <ol class="breadcrumb text-right">
                                    <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                                    <li><a href="#">Products</a></li>
                                    <li class="active">Edit Product</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <strong>Edit Product</strong> Form
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'admin-edit-product' product.pk%}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Product ID :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{product.pk}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Product Name :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{product.pname}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Category :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{form8.category}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Amount :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form8.price }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">Photo :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form8.image }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">Description :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form8.description }}
                                        </div>
                                    </div>

                                    <div class="row form-group">
                                        <button type="submit" class="btn btn-outline-secondary">
                                            Submit
                                        </button>
                                        <button type="reset" class="btn btn-outline-secondary">
                                            Reset
                                        </button>
                                    </div>
                                </form>
                            </div>

                        </div>
                  </div>
            </div>
        </div>
{% endblock %}

CollegeMart-master/collegemart/accounts/templates/my template/admin_edit_profile.html
{% extends 'my template/demo_body.html' %}
{% load static %}
{% block script %}
    <script type="text/javascript">
        $(function () {
            $('#id_fname').addClass("form-control mb-4");
            $('#id_lname').addClass("form-control mb-4");
            $('#id_phone').addClass("form-control mb-4");
            $('#id_bio').addClass("form-control mb-4");
            $('#id_photo').addClass("form-control-file");
            $( "#id_dob" ).datepicker({
                                        changeMonth: true,
                                        changeYear: true,
                                        yearRange: "1990:2017",
                                    })
        });

    </script>


{% endblock %}
{% block table %}
    <div class="p1">
        <div class="content">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header" style="background-color: #fbb710; color: white">
                            <strong class="card-title mb-3">Old Profile</strong>
                        </div>
                    <div class="row">
                        <div class="col-md-4">
                            <aside class="profile-nav alt">
                                <section class="card">


                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                            <strong>Username:</strong> {{ u.username }}
                                        </li>
                                        <li class="list-group-item">
                                            <strong>Full Name:</strong> {{ profile.fname }}&nbsp;{{ profile.lname }}
                                        </li>
                                        <li class="list-group-item">
                                            <i class="fa fa-envelope-o"></i> {{ u.email }}
                                        </li>
                                        <li class="list-group-item">
                                            <i class="fa fa-phone"></i> {{ profile.phone }}
                                        </li>
                                        <li class="list-group-item">
                                            <i class="fa fa-calendar"></i> {{ profile.dob }}
                                        </li>
                                        <li class="list-group-item">
                                            <strong>Bio:</strong><br>
                                            <p>
                                            {{ profile.bio }}
                                            </p>
                                        </li>
                                    </ul>

                                </section>
                            </aside>
                        </div>
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body" style="height: 100%">
                                    <img class="card-img-top" src='{{ profile.photo.url }}' alt="Card image cap" style="height: 300px;width: 242px;">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bootstrap-iso">
        <div class="content">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header" style="background-color: #fbb710; color: white">
                                <strong>Edit Profile</strong> Form
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'edit-my-profile' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Username :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{u.username}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">First Name :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ p_form.fname }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Last Name :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ p_form.lname }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">DOB :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ p_form.dob }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Phone No :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ p_form.phone }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">Photo :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ p_form.photo }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">Bio :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{ p_form.bio }}
                                        </div>
                                    </div>

                                    <div class="row form-group">
                                        <button type="submit" class="btn btn-outline-secondary">
                                            Submit
                                        </button>
                                        <button type="reset" class="btn btn-outline-secondary">
                                            Reset
                                        </button>
                                    </div>
                                </form>

                            </div>

                        </div>
                  </div>
            </div>
        </div>
    </div>
{% endblock %}

CollegeMart-master/collegemart/accounts/templates/my template/admin_edit_user_form.html
{% extends 'my template/demo_body.html' %}
{% block script %}
    <script type="text/javascript">
        $(function () {
            $('#id_email').addClass("form-control mb-4");

        });

    </script>
{% endblock %}

{% block table %}
        <div class="breadcrumbs">
            <div class="breadcrumbs-inner">
                <div class="row m-0">
                    <div class="col-sm-4">
                        <div class="page-header float-left">
                            <div class="page-title">
                                <h1>Dashboard</h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="page-header float-right">
                            <div class="page-title">
                                <ol class="breadcrumb text-right">
                                    <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                                    <li><a href="{% url 'user-show' %}">Users</a></li>
                                    <li class="active">Edit user</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="animated fadeIn">
                <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <strong>Edit User</strong> Form
                            </div>
                            <div class="card-body card-block">
                                <form action="{% url 'admin-edit-user' user.pk %}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    {% csrf_token %}
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">User ID :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{user.pk}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Username :</label></div>
                                        <div class="col-12 col-md-9">
                                            {{user.username}}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="text-input" class=" form-control-label">Old Email :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ user.email }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="file-input" class=" form-control-label">New Email :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form7.email }}
                                        </div>
                                    </div>
                                    <div class="row form-group">
                                        <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">Activate account :</label></div>
                                        <div class="col-12 col-md-9">
                                                {{ form7.is_active }}<br>
                                            <p>Tick here to activate the user</p>
                                        </div>
                                    </div>

                                    <div class="row form-group">
                                        <button type="submit" class="btn btn-outline-secondary">
                                            Submit
                                        </button>
                                        <button type="reset" class="btn btn-outline-secondary">
                                            Reset
                                        </button>
                                    </div>
                                </form>
                            </div>

                        </div>
                  </div>
            </div>
        </div>
{% endblock %}