CollegeMart-master/collegemart/buyer/urls.py
from django.urls import path, include
from . import views
from cart import views as cart_views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'buyer'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('shop/<int:rec>', views.shop_list, name='shop'),
    path('shop/<int:rec>/<int:cid>/<int:sid>', views.shop_filters, name='shop-filters'),
    path('shop/<int:cid>/<int:rec>', views.shop_category, name='shop-category'),
    path('shop/item/<int:pid>/<int:rec>', views.shop_item, name='shop-item'),
    path('', views.home, name='home'),
    path('checkout/', views.checkout, name="checkout"),
    path('search/', views.search, name='search'),
    path('order/', views.order_create, name='order'),
    path('order/cancel/<pid>', views.order_cancellation, name='order-cancellation'),
    path('shop/sort_product', views.sort_products, name="sort_product")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<rec>\d+)$', views.cart_remove, name='cart_remove'),
]

CollegeMart-master/collegemart/collegemart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from buyer.views import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('paytm.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
    path('feedback/', include('feedback.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollegeMart-master/collegemart/cart/models.py
from django.db import models

# Create your models here.

CollegeMart-master/collegemart/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

CollegeMart-master/collegemart/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from seller.models import Products_Selling as Product
from seller.models import Products_Leasing as Product2
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

@login_required
@require_POST
def cart_add(request, product_id, rec):
    cart = Cart(request)  # create a new cart object passing it the request object
    rec = int(rec)
    if rec == 0:
        #print('a')
        product = get_object_or_404(Product, id=product_id)
    elif rec:
        #print('b')
        product = get_object_or_404(Product2, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, rec=rec, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')

@login_required
def cart_remove(request, product_id, rec):
    cart = Cart(request)
    rec = int(rec)
    if rec == 0: 
        product = get_object_or_404(Product, id=product_id)
    else:
        product = get_object_or_404(Product2, id=product_id)
    cart.remove(product, rec)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

CollegeMart-master/collegemart/cart/templates/cart/detail.html
{% extends 'buyer/base.html' %}
{% load static %}
{% block content %}
        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                            <h2>Shopping Cart
                            <span class="badge pull-right">
                                {% with total_items=cart|length %}
                                    {% if cart|length > 0 %}
                                        My Shopping Order:
                                        <a href="{% url "cart:cart_detail" %}" style="color: #00000">
                                            {{ total_items }} item {{ total_items|pluralize }}, ₹{{ cart.get_total_price }}
                                        </a>
                                        {% else %}
                                        Your cart is empty.
                                    {% endif %}
                                {% endwith %}
                            </span>
                            </h2>
                        </div>

                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                        {% with product=item.sproduct %}
                                            {% if product %}
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="#"><img src="{{ product.image.url }}" alt="Product" style="width:166px; height:166px;"></a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{ product.pname }}</h5>
                                        </td>
                                        <td class="price">
                                            <span>₹{{ product.price }}</span>
                                        </td>
                                        <td class="qty">
                                            <div class="qty-btn d-flex">
                                                <p>Qty</p>
                                                <div class="quantity">
                                                    <input type="number" class="qty-text" id="qty" step="1" min="1" max="{{ product.stock }}" name="quantity" value="{{ item.quantity }}">
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">
                                            <a href="{% url "cart:cart_remove" product.id item.rec %}">Remove</a>
                                        </td>
                                    </tr>
                                            {% endif %}
                                        {% endwith %}
                                    {% endfor %}
                                    {% for item in cart %}
                                        {% with product=item.lproduct %}
                                            {% if product %}
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="#"><img src="{{ product.image1.url }}" alt="Product" style="width:166px; height:166px;"></a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{ product.pname1 }}</h5>
                                        </td>
                                        <td class="price">
                                            <span>₹{{ product.price1 }}</span>
                                        </td>
                                        <td class="qty">
                                            <div class="qty-btn d-flex">
                                                <p>Qty</p>
                                                <div class="quantity">
                                                    <input type="number" class="qty-text" id="qty" step="1" min="1" max="{{ product.stock }}" name="quantity" value="{{ item.quantity }}">
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">
                                            <a href="{% url "cart:cart_remove" product.id item.rec %}">Remove</a>
                                        </td>
                                    </tr>
                                            {% endif %}
                                        {% endwith %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>Subtotal:</span> <span>₹{{ cart.get_total_price }}</span></li>
                                <li><span>Delivery:</span> <span>Free</span></li>
                                <li><span>Total:</span> <span>₹{{ cart.get_total_price }}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <a href="{% url 'buyer:checkout' %}" class="btn amado-btn w-100">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
{% endblock %}

CollegeMart-master/collegemart/cart/templates/cart/detail1.html
{% extends 'buyer/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #00000">
                            {{ total_items }} item {{ total_items|pluralize }}, ₹{{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>₹{{ item.price }}</td>
                            <td>₹{{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>₹{{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "buyer:shop" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'buyer:checkout' %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}